services:
  mysql_curso:
    container_name: mysql_curso
    image: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default_time_zone=America/Sao_Paulo
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql